// Create web server
// 1. npm init
// 2. npm install express --save
// 3. npm install body-parser --save
// 4. npm install mongoose --save
// 5. npm install nodemon --save-dev
// 6. npm install cors --save
// 7. npm install dotenv --save
// 8. npm install helmet --save
// 9. npm install morgan --save
// 10. npm install jsonwebtoken --save
// 11. npm install bcrypt --save
// 12. npm install multer --save
// 13. npm install uuid --save
// 14. npm install nodemailer --save
// 15. npm install nodemailer-smtp-transport --save
// 16. npm install nodemailer-sendgrid-transport --save
// 17. npm install express-rate-limit --save
// 18. npm install express-mongo-sanitize --save
// 19. npm install xss-clean --save
// 20. npm install hpp --save
// 21. npm install @hapi/joi --save
// 22. npm install --save-dev jest
// 23. npm install --save-dev supertest
// 24. npm install --save-dev jest-mongodb
// 25. npm install --save-dev @shelf/jest-mongodb
// 26. npm install --save-dev @types/jest
// 27. npm install --save-dev ts-jest
// 28. npm install --save-dev @types/supertest
// 29. npm install --save-dev ts-node
// 30. npm install --save-dev @types/node
// 31. npm install --save-dev @types/express
// 32. npm install --save-dev @types/bcrypt
// 33. npm install --save-dev @types/multer
// 34. npm install --save-dev @types/uuid
// 35. npm install --save-dev @types/nodemailer
// 36. npm install --save-dev @types/nodemailer-smtp-transport
// 37. npm install --save-dev @types/nodemailer-sendgrid-transport
// 38. npm install --save-dev @types/express-rate-limit
// 39. npm install --save-dev @types/express-mongo-sanitize